<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="deg_to_rad" value="0.01745329251994329577"/>
    <!-- Adding other macros -->
    <xacro:include filename="$(find pointgrey_camera_description)/urdf/pointgrey_flea3.urdf.xacro"/>
    <xacro:include filename="$(find lms1xx)/urdf/sick_lms1xx.urdf.xacro"/>

    <xacro:macro name="prometheus" params="length width wheel_radius height">
        <!-- Links: inertial,visual,collision -->
        <link name="base_link">
            <inertial>
                <!-- origin is relative -->
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="2"/>
                <inertia ixx="1" ixy="0" ixz="0"
                        iyy="1" iyz="0"
                        izz="1"/>
            </inertial>
            <visual>
                <!-- <origin xyz="${length/2} ${-width/2-0.15} ${-wheel_radius+0.05}" rpy="0 0 0"/> -->
                <origin xyz="${length/2} ${-width+0.09} ${wheel_radius}" rpy="${90 * deg_to_rad} 0 ${180 * deg_to_rad}"/>
                <geometry>
                    <mesh filename="file:///$(find prometheus_description)/meshes/chassis.dae"/>
                </geometry>
            </visual>
            <collision>
                <!-- origin is relative -->
                <origin xyz=" 0 0 ${-wheel_radius + height/2}"/>
                <geometry>
                    <box size="${length} ${width} ${height/2}"/>
                </geometry>
            </collision>
        </link>

        <link name="base_footprint">
            <collision>
                <origin xyz="0 0 0"/>
                <geometry>
                    <sphere radius="0.00000001"/>
                </geometry>
            </collision>
        </link>
        <joint name="base_footprint_joint" type="fixed">
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
            <child link="base_link"/>
            <parent link="base_footprint"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="kinect" params="name x y z roll pitch yaw">
        <joint name="kinect_${name}_joint" type="fixed">
            <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}"/>
            <parent link="base_link"/>
            <child link="kinect_${name}_link"/>
        </joint>

        <link name="kinect_${name}_link">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://traxxas_description/meshes/kinect.dae"/>
                </geometry>
            </visual>
            <collision>
                <geometry>
                    <box size="0.06 0.30 0.07"/>
                </geometry>
            </collision>
        </link>


        <joint name="kinect_${name}_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="0 0 -1.5708"/>
            <parent link="kinect_${name}_link"/>
            <child link="kinect_${name}_optical_frame"/>
        </joint>
    </xacro:macro>


</robot>