<?xml version="1.0"?>
<robot name="prometheus" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!--
    Robot model taken from http://wiki.ros.org/pr2_mechanism/Tutorials/SImple%20URDF-Controller%20Example
    -->
    <xacro:include filename="$(find prometheus_description)/urdf/prometheus_wheel.urdf.xacro"/>
    <xacro:include filename="$(find prometheus_description)/urdf/prometheus_ackermann.macro.urdf.xacro"/>
    <xacro:property name="deg_to_rad" value="0.01745329251994329577"/>
    <!-- Constants for robot dimensions -->
    <xacro:property name="length" value="0.6" />
    <xacro:property name="width" value="0.35" />
    <xacro:property name="height" value="0.5"/>
    <xacro:property name="length_offset" value="0"/>
    <xacro:property name="height_offset" value="0"/>
    <xacro:property name="wheel_radius" value="0.06" /> <!-- Link 1 -->
    <xacro:property name="thickness" value="0.032" /> <!-- Link 2 -->
    <!--  we need two because the car isn't a square-->
    <xacro:property name="axel_offset_x" value="0.5" /> <!-- Space btw top of beam and the each joint -->
    <xacro:property name="axel_offset_y" value="0" /> <!-- Space btw top of beam and the each joint -->
    <xacro:property name="steer_offset" value="0.02" /> <!-- Link 1 -->

    <!-- Add car macro -->
    <xacro:prometheus length="${length}" width="${width}" height="${height}" wheel_radius="${wheel_radius}"/>

    <!--    Add sensors-->

    <!-- joints for ackermann_steering_controller -->
    <xacro:front_steer name="front" parent="base" radius="${wheel_radius}" thickness="${thickness}"
                       length="${length}" width="${width}" axel_offset="${axel_offset_x}" steer_height="${wheel_radius+steer_offset}">
        <origin xyz="${length/2-axel_offset_x} 0 0" rpy="${-90 * deg_to_rad} 0 ${90 * deg_to_rad}"/>
    </xacro:front_steer>
    <xacro:rear_wheel name="rear" parent="base" radius="${wheel_radius}" thickness="${thickness}">
        <origin xyz="${-length/2+axel_offset_x} 0 0" rpy="${-90 * deg_to_rad} 0 ${-90 * deg_to_rad}"/>
    </xacro:rear_wheel>

    <!-- Wheels -->
    <xacro:front_wheel_lr name="front_right" parent="base" radius="${wheel_radius}" thickness="${thickness}"
                          length="${2*length + 0.1}" width="${width}" axel_offset="${axel_offset_x}" right_left="1" steer_height="${wheel_radius+steer_offset}">
        <origin xyz="${length/2-axel_offset_x + 0.05} ${width/2+axel_offset_y} 0" rpy="${-90 * deg_to_rad} 0 0"/>
    </xacro:front_wheel_lr>
    <xacro:front_wheel_lr name="front_left" parent="base" radius="${wheel_radius}" thickness="${thickness}"
                          length="${2*length + 0.1}" width="${width}" axel_offset="${axel_offset_x}" right_left="-1" steer_height="${wheel_radius+steer_offset}">
        <origin xyz="${length/2-axel_offset_x + 0.05} ${-width/2-axel_offset_y} 0" rpy="${-90 * deg_to_rad} 0 0"/>
    </xacro:front_wheel_lr>
    <xacro:rear_wheel_lr name="rear_right" parent="base" radius="${wheel_radius}" right_left="1" thickness="${thickness}">
        <origin xyz="${length/2-axel_offset_x + 0.05} ${width/2+axel_offset_y} 0" rpy="${-90 * deg_to_rad} 0 ${-90 * deg_to_rad}"/>
    </xacro:rear_wheel_lr>
    <xacro:rear_wheel_lr name="rear_left" parent="base" radius="${wheel_radius}" right_left="-1" thickness="${thickness}">
        <origin xyz="${length/2-axel_offset_x + 0.05} ${-width/2-axel_offset_y} 0" rpy="${-90 * deg_to_rad} 0 ${90 * deg_to_rad}"/>
    </xacro:rear_wheel_lr>

    <!-- Gazebo plugin for ROS Control -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotSimType>steer_bot_hardware_gazebo/SteerBotHardwareGazebo</robotSimType>
        </plugin>
    </gazebo>

    <!-- Colour -->
    <gazebo reference="base_footprint">
        <material>Gazebo/Purple</material>
    </gazebo>

</robot>